### ISSUE TITLE
Weird recognition of Elsevier content

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/CitationHelperForSE#7]
Observed for: https://doi.org/10.1016/S0010-8545(02)00102-9  
Also: https://www.sciencedirect.com/science/article/pii/S0010854502001029  
and plain DOI.

Result: 
```
1. Gillespie, R. The octet rule and hypervalence: two misunderstood concepts. *Coordination Chemistry Reviews* **2002,** *233-234undefined 53–62. [DOI: 10.1016/S0010-8545(02)00102-9](https://doi.org/10.1016/S0010-8545(02)00102-9).
```

Weirder, when trying to insert another (10.1021/ic00108a032) it'll produce:

```
### References:

1. Gillespie, R. The octet rule and hypervalence: two misunderstood concepts. *Coordination Chemistry Reviews* **2002,** *233-234undefined 53–6
2. Gillespie, R. J.; Robinson, E. A. Hypervalence and the Octet Rule. *Inorg. Chem.* **1995,** *34* (4), 978–979. [DOI: 10.1021/ic00108a032](https://doi.org/10.1021/ic00108a032).
3. [DOI: 10.1016/S0010-8545(02)00102-9](https://doi.org/10.1016/S0010-8545(02)00102-9).
```

Aparently the `2.` at the end gets interpreted as the next item point. The insertion of the markers is also quite wrong...

---

Adding a new reference bevor the first worked.

**Comment by GaurangTandon** [comment]
Thanks for the report, I attempted a fix in the dev branch. Please let me know if that fixes the issue.

**Comment by polyluxus** [comment]
Example works now, but following Science direct is broken:
- https://www.sciencedirect.com/science/article/pii/S1756464618303517
- https://www.sciencedirect.com/science/article/pii/S1756464618303517?via%3Dihub

doi/doi-url works

Console:
```
userscript.html?id=b350ce98-23b6-4680-a422-172546652034:776 GET https://api.crossref.org/works/10.1016/S1756-4646(18)30351-7 404 (Not Found)
getDOIMetaData @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:776
chse.citeDOI @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:804
(anonymous) @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:1110
VM108:1 Uncaught SyntaxError: Unexpected token R in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhttp.onload (userscript.html?id=b350ce98-23b6-4680-a422-172546652034:779)
xhttp.onload @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:779
load (async)
getDOIMetaData @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:778
chse.citeDOI @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:804
(anonymous) @ userscript.html?id=b350ce98-23b6-4680-a422-172546652034:1110

**Comment by GaurangTandon** [comment]
Are you sure the URL - https://www.sciencedirect.com/science/article/pii/S1756464618303517 - used to work previously? Because, a quick peek into the console reveals that the fetch URL is correctly interpreted as: `https://api.crossref.org/works/10.1016/S1756-4646(18)30351-7`, compared to the first DOI on this page `10.1016/S0010-8545(02)00102-9`.

However, if you contrast the [working webpage](https://www.sciencedirect.com/science/article/pii/S0010854502001029?via%3Dihub) with the [nonworking page](https://www.sciencedirect.com/science/article/pii/S1756464618303517), you'll notice that the DOI listed on the first page matches with the URL. However, it does not match in the second case.

This has been a recurring problem with sciencidirect.com URLs. However, if you use the corresponding DOI in the second case (`https://doi.org/10.1016/j.jff.2018.07.016`), the thing works perfectly.

**Comment by polyluxus** [comment]
No I am not sure it ever worked. When I tried to build a test set, I came across this broken link and posted it here. I remember that there always were problems with siencedirect URLs, when they do not contain the doi. I have no clue how to work around that.

**Comment by GaurangTandon** [comment]
Alright. So, till then I'm closing this issue.
